### ISSUE TITLE
BlockSix/Edit

### ISSUE THREAD

**Issue by hhkimmm9** [hhkimmm9/Dashboard#10]
## Tasks

- Users should be able to edit today's task
- Users should be able to add comments to their tasks

## From Server

- 

## Frontend

- [ ] Since it needs more space than the blocksix/show page does due to comment section (seeing all tasks at once has higher priority in show page) << 이거 스케치 단계에서 정했어야지 왜 여기서 정하고 앉아잇냐 그러니까 이렇게 길어지잖아,  planning to add three icons which represents morning, afternoon, and evening respectively. They will switch the content of the page, and each page shows tasks contained in each section.

## To Server

- [ ] updated tasks keyword/description
- [ ] comments

## Backend

- [ ] 

## API References

- PATCH /tasks/{id}
- POST /comments
- PATCH /comments/{id}
- DELETE /comments/{id}

## Assets

- N/A

## External Libraries

- Tippy.js

## Security

-

**Comment by adityakode** [comment]
Hi ! would love to help!
can you explain this issue?

**Comment by hhkimmm9** [comment]
oh wow cool! I didn't expect anyone shows up here 😄

It's just my personal project but if you are really intereseted in joinning this project please send me a DM.

Thanks!
